name: chaos-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - requests
  - pandas
  - seaborn
  - click
  - openpyxl
  - scikit-plot
  - pip
  - pip:
    - pynt
    - pynt-contrib
    - paver
  - luigi
  - path.py